### ISSUE TITLE
Restrict ESLint rules to LWC

### ISSUE THREAD

**Issue by Bartheleway** [salesforce/eslint-config-lwc#11]
Hi,

I'm working in a environnement which has both LWC and Aura Component. Is it possible to disable LWC rules for the aura folder ?

Best regards,
Barthélemy

**Comment by muenzpraeger** [comment]
The rules are applied based on where the `.eslintrc.json` is located. On default projects the VS Code Salesforce LWC extension places it within the `lwc` folder, so they only apply against anything within that folder and it’s sub folders.

See [here](https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/.eslintrc.json) an example.

**Comment by pmdartus** [comment]
You can find more details on how to configure eslint on the official eslint website: [configuration-cascading-and-hierarchy](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)
