### ISSUE TITLE
Rule to error when HTML attributes are set during construction

### ISSUE THREAD

**Issue by kevinv11n** [salesforce/eslint-config-lwc#14]
Per https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance

> The element's attributes and children must not be inspected, as in the non-upgrade case none will be present, and relying on upgrades makes the element less usable.

Thus code like this fails:

```
import { LightningElement } from 'lwc';
export default class Example extends LightningElement {
    id = "123";
}
```

Because it's transpiled to this:
```
class Example extends lwc.LightningElement {
      constructor(...args) {
        super(...args);
        this.id = "123";
      }
}
```

Ad `this.id="123"` invokes the setter trap setup at https://github.com/salesforce/lwc/blob/master/packages/@lwc/engine/src/framework/base-lightning-element.ts#L567-L579

**Comment by pmdartus** [comment]
Duplicate https://github.com/salesforce/eslint-plugin-lwc/issues/26.
