### ISSUE TITLE
'@salesforce/eslint-config-lwc@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by jesusbarcenilla** [salesforce/eslint-config-lwc#35]
Hi,

It seems the package is not longer available in npm. 

it can be tested with: 

`npm i @salesforce/eslint-config-lwc`
or
`npm info @salesforce/eslint-config-lwc`

**Comment by muenzpraeger** [comment]
It's [available](https://www.npmjs.com/package/@salesforce/eslint-config-lwc), and can be installed.

Are you using a custom npm server?

**Comment by jesusbarcenilla** [comment]
No, and I could reproduce the error locally and in a bitbucket CI infrastructure.

**Comment by muenzpraeger** [comment]
Weird. That's my output.

 ☁   testing  npm config get
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.5 node/v12.13.0 darwin x64"

; userconfig /Users/rwinkelmeyer/.npmrc
registry = "https://registry.npmjs.org/"

![2020-08-06_12-22-46 (1)](https://user-images.githubusercontent.com/2205451/89521546-fd906900-d7df-11ea-997f-f9d27bc8a95b.gif)

**Comment by jesusbarcenilla** [comment]
It looks like the problem is in npm side. 

https://status.npmjs.org/

> We are still looking into error telemetry for installation of scoped packages but are seeing signs of improvement.

Sorry, I should have check in npm before open this ticket.

Thank you very much for your quick response.
