### ISSUE TITLE
LWC1112: @api get connection and @api set connection detected in class declaration. Only one of the two needs to be decorated with @api.

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/eslint-config-lwc#66]
When a Set is before a Get and it is annotaded with @api eslint indicates the following error:

`LWC1112: @api get connection and @api set connection detected in class declaration. Only one of the two needs to be decorated with @api.`

![image](https://user-images.githubusercontent.com/55927613/125073064-d4342900-e091-11eb-8791-f975723d505a.png)

When the Set is below the Get the issue is fixed, but eslint does not recommend this. The order of Get and Set should not be considered on this rule.

![image](https://user-images.githubusercontent.com/55927613/125073158-eca44380-e091-11eb-98a2-c74ad5fd3768.png)

**Comment by nolanlawson** [comment]
Thanks for reporting. Just to be clear, which eslint preset/rule recommends putting `set` after `get`?

Also, does it work for you if you move the `@api` before the `set`? This should work:

```js
  _foo

  get foo () {
    return this._foo
  }

  @api
  set foo (val) {
    this._foo = val
  }
```

**Comment by AllanOricil** [comment]
@nolanlawson  this is the text that appears when I hover over the lint error


````
c:\Users\allan_000\workspace\vodafone\sf-metadata\agentAllFlowsNewIssueEnglish.js: LWC1112: @api get connection and @api set connection detected in class declaration. Only one of the two needs to be decorated with @api.lwc
(property) agentAllFlowsNewIssueEnglish.connection: any
````

These scenarios also do not work

![image](https://user-images.githubusercontent.com/55927613/125118181-b5e82080-e0c5-11eb-843a-6d922965e5a9.png)
![image](https://user-images.githubusercontent.com/55927613/125118214-c1d3e280-e0c5-11eb-939a-5f5c66dbd935.png)
![image](https://user-images.githubusercontent.com/55927613/125118240-cc8e7780-e0c5-11eb-8452-1d9faaf64256.png)


This is the only way that makes it work

![image](https://user-images.githubusercontent.com/55927613/125118271-dca65700-e0c5-11eb-99d7-170be0830105.png)

**Comment by AllanOricil** [comment]
I just noticed that this is not an ESLint error. It is a `lwc` api error.  Should I move this error to the lwc repository or leave it here?

**Comment by AllanOricil** [comment]
This is how my `.eslintrc` is configured


````json
{
  "extends": ["@salesforce/eslint-config-lwc/recommended"]
}
````

**Comment by AllanOricil** [comment]
@nolanlawson I found that this issue was resolved in 2019 
https://github.com/salesforce/lwc/issues/1113

I will close this issue here

**Comment by ytiq** [comment]
found an example that fails it @AllanOricil .

```
import { LightningElement, api } from 'lwc';

export default class Testsdfsdf extends LightningElement {
    @api get b() {}
    @api set a(value) { }
    get a() {}
}
```

If anywhere in your code you have @api getter, then it fails other parts where you have @api setter

**Comment by AllanOricil** [comment]
> found an example that fails it @AllanOricil .
> 
> ```
> import { LightningElement, api } from 'lwc';
> 
> export default class Testsdfsdf extends LightningElement {
>     @api get b() {}
>     @api set a(value) { }
>     get a() {}
> }
> ```
> 
> If anywhere in your code you have @api getter, then it fails other parts where you have @api setter
@ytiq The example I showed above was fixed after I reopened vscode. I think the language server that has the rules was not loaded somehow. But anyway, I will reopen this issue, and then we wait for @nolanlawson to help us.

**Comment by ytiq** [comment]
I was getting error on existing code base, tried re-opening. Also tried making new components and testing with them. Once you have mix of `@api getter` and `@api setters` in one file, lwc-server stops working

**Comment by AllanOricil** [comment]
@pmdartus @nolanlawson I confirm ytiq isolated the problem correctly. It is not an issue related to vscode not loading the language server.



steps:

1 - create a lwc with the following code
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
}
````
2 - verify it does work and no language server error is present
3 - change the lwc code to this one
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
    @api get bla(){}
}
````
4 - verify that now you have the error from this issue

**Comment by pmdartus** [comment]
As far as I understand the issue, it is reported by the language server running an outdated version of the LWC compiler and is unrelated to the eslint plugin. I will close this issue in favor of https://github.com/forcedotcom/lightning-language-server/issues/464.

**Comment by ytiq** [comment]
@pmdartus lightning-language-server is not being updated, do you know, by any chance who maintains the VS code plugin, so I can write the issue in the correct place? Because this issue makes the plugin unusable.

**Comment by pmdartus** [comment]
@seksenov Do you know who owns the lightning language server VSCode extension?
