### ISSUE TITLE
Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/eslint-config-lwc#67]
For some reason eslint is saying import is wrong. It might be related to this issue https://github.com/yannickcr/eslint-plugin-react/issues/447#issuecomment-184617282

![image](https://user-images.githubusercontent.com/55927613/125073397-43118200-e092-11eb-93ab-fba15069f739.png)

**Comment by AllanOricil** [comment]
I fixed this issue after creating an `.eslintrc` file with the following configs

````json
{
  "parserOptions": {
      "sourceType": "module",
      "ecmaVersion": 2020
  }
}
````

**Comment by AllanOricil** [comment]
Oh I found a better solution. I just created the `.eslintrc` with the content from the README

````json
{
    "extends": ["@salesforce/eslint-config-lwc/recommended"]
}
````

For some reason `sfdx force:project:create` did not create the .eslintrc

**Comment by AlexRixten** [comment]
Thank you, it was useful for me!)

**Comment by MadyKramer** [comment]
Thanks :)
